server:
  port: 8085
spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8081/
        predicates:
        - Path=/students/**
        filters:
          - name: CircuitBreaker
            args:
              name: Project1
              fallbackuri: forward:/project1FallBackMethod
      - uri: http://localhost:8082/
        predicates:
        - Path=/v2/students/**
        filters:
          - name: CircuitBreaker
            args:
              name: Project2
              fallbackuri: forward:/project2FallBackMethod
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
