server:
  port: 8085
spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8081/
        predicates:
        - Path=/students/**
      - uri: http://localhost:8082/
        predicates:
        - Path=/students/**
